language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

  - if [[ $PHPCS != 1 ]]; then composer require phpunit/phpunit:"*"; fi

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml --ignore=vendor,docs . ; fi"

notifications:
  email: false
